In [11]:
import pandas as pd
# Create the dataset

data = {'ID': ['Eth - 101', 'Eth – 102', 'Eth - 103', 'Eth - 104', 'Eth - 105'],
'Name': [' Haileslassie Zeferu Abel', ' Worku Abenezer Girma', ' Abenezer Reta Tamirat', ' Abraham Melisew Fireda', ' Hailu Abraham Niguse'],
'Age': [25, None, 29, 33, None],
'Salary': [55000, 48000, None, 62000, None]
}

df = pd.DataFrame(data)
                 

# df=pd.DataFrame(data.fillna())

In [21]:
df.describe()

            Age        Salary
count   8.00000      8.000000
mean   29.50000  55000.000000
std     2.56348   5291.502622
min    25.00000  48000.000000
25%    29.00000  53250.000000
50%    29.00000  55000.000000
75%    30.00000  56750.000000
max    33.00000  62000.000000

In [6]:
df

          ID                       Name   Age   Salary
0  Eth - 101   Haileslassie Zeferu Abel  25.0  55000.0
1  Eth – 102       Worku Abenezer Girma   NaN  48000.0
2  Eth - 103      Abenezer Reta Tamirat  29.0      NaN
3  Eth - 104     Abraham Melisew Fireda  33.0  62000.0
4  Eth - 105       Hailu Abraham Niguse   NaN      NaN

In [26]:
df_clean=df.dropna()
print(df_clean)

          ID                      Name  Age  Salary         City
0  Eth - 101  Haileslassie Zeferu Abel   25   55000  Addis Ababa
1  Eth - 102      Worku Abenezer Girma   29   48000        Adama
2  Eth - 103     Abenezer Reta Tamirat   29   55000  Addis Ababa
3  Eth - 104    Abraham Melisew Fireda   33   62000        Adama
4  Eth - 105      Hailu Abraham Niguse   29   55000  Addis Ababa
5  Eth - 102       WorkuAbenezer Girma   29   48000        Adama
6  Eth - 104    Abraham Melisew Fireda   33   62000        Adama
7  Eth - 106      Hailu Abraham Niguse   29   55000  Addis Ababa

In [7]:
df.describe()

        Age   Salary
count   3.0      3.0
mean   29.0  55000.0
std     4.0   7000.0
min    25.0  48000.0
25%    27.0  51500.0
50%    29.0  55000.0
75%    31.0  58500.0
max    33.0  62000.0

In [28]:
# for column in df.columns:
#  if df[column].dtype == 'float64' or df[column].dtype == 'int64':
#      df[column].fillna(df[column].mean(), inplace=True)
# print(df)

for column in df.columns:
    if df[column].dtype=='float64' or df[column].dtype=='int64':
        df[column].fillna(df[column].mean() ,inplace=True)
print(df)

          ID                      Name  Age  Salary         City
0  Eth - 101  Haileslassie Zeferu Abel   25   55000  Addis Ababa
1  Eth - 102      Worku Abenezer Girma   29   48000        Adama
2  Eth - 103     Abenezer Reta Tamirat   29   55000  Addis Ababa
3  Eth - 104    Abraham Melisew Fireda   33   62000        Adama
4  Eth - 105      Hailu Abraham Niguse   29   55000  Addis Ababa
5  Eth - 102       WorkuAbenezer Girma   29   48000        Adama
6  Eth - 104    Abraham Melisew Fireda   33   62000        Adama
7  Eth - 106      Hailu Abraham Niguse   29   55000  Addis Ababa

/tmp/ipykernel_938575/4034959948.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[column].fillna(df[column].mean() ,inplace=True)

In [17]:
import pandas as pd
# Create the dataset
data = {'ID': ['Eth - 101', 'Eth – 102', 'Eth - 103', 'Eth - 104', 'Eth - 105'],
'Name': [' Haileslassie Zeferu Abel', ' Worku Abenezer Girma', ' Abenezer Reta Tamirat', ' Abraham Melisew Fireda', ' Hailu Abraham Niguse'],
'Age': [25, None, 29, 33, None],
'Salary': [55000, 48000, None, 62000, None]}
df = pd.DataFrame(data)
# Remove rows with missing values
df_cleaned = df.dropna()
print(df_cleaned)

          ID                       Name   Age   Salary
0  Eth - 101   Haileslassie Zeferu Abel  25.0  55000.0
3  Eth - 104     Abraham Melisew Fireda  33.0  62000.0

In [19]:
import pandas as pd
# Sample dataset
data = {'ID': ['Eth - 101', 'Eth - 102', 'Eth - 103', 'Eth - 104', 'Eth - 105', 'Eth - 102', 'Eth - 104', 'Eth - 106'],
'Name': ['Haileslassie Zeferu Abel', 'Worku Abenezer Girma', 'Abenezer Reta Tamirat', 'Abraham Melisew Fireda', 'Hailu Abraham Niguse', 'WorkuAbenezer Girma', 'Abraham Melisew Fireda', 'Hailu Abraham Niguse'],
'Age': [25, 29, 29, 33, 29, 29, 33, 29],
'Salary': [55000, 48000, 55000, 62000, 55000, 48000, 62000, 55000],
'City': ['Addis Ababa', 'Adama', 'Addis Ababa', 'Adama', 'Addis Ababa', 'Adama', 'Adama', 'Addis Ababa']}

# Original Dataset
df = pd.DataFrame(data)
print("Original Dataset")
print(df, '\n')

Original Dataset
          ID                      Name  Age  Salary         City
0  Eth - 101  Haileslassie Zeferu Abel   25   55000  Addis Ababa
1  Eth - 102      Worku Abenezer Girma   29   48000        Adama
2  Eth - 103     Abenezer Reta Tamirat   29   55000  Addis Ababa
3  Eth - 104    Abraham Melisew Fireda   33   62000        Adama
4  Eth - 105      Hailu Abraham Niguse   29   55000  Addis Ababa
5  Eth - 102       WorkuAbenezer Girma   29   48000        Adama
6  Eth - 104    Abraham Melisew Fireda   33   62000        Adama
7  Eth - 106      Hailu Abraham Niguse   29   55000  Addis Ababa

In [20]:
df_cleaned = df.drop_duplicates()
print("Duplicates Removed - Exact Match")
print(df_cleaned, '\n')

Duplicates Removed - Exact Match
          ID                      Name  Age  Salary         City
0  Eth - 101  Haileslassie Zeferu Abel   25   55000  Addis Ababa
1  Eth - 102      Worku Abenezer Girma   29   48000        Adama
2  Eth - 103     Abenezer Reta Tamirat   29   55000  Addis Ababa
3  Eth - 104    Abraham Melisew Fireda   33   62000        Adama
4  Eth - 105      Hailu Abraham Niguse   29   55000  Addis Ababa
5  Eth - 102       WorkuAbenezer Girma   29   48000        Adama
7  Eth - 106      Hailu Abraham Niguse   29   55000  Addis Ababa